name: Deploy FastAPI with SeleniumBase to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Railway CLI
        uses: MadeByThePinsHub/setup-railway-cli-action@v0.1.0
        with:
          npm-mode: true  # instala @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up
